name: auto-hmmer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential gcc python3 python3-pip
          pip install wget
          pip install biopython
          tar -xvf hmmer.tar.gz
          cd hmmer-3.3.2
          ./configure
          make
          sudo make install
          export PATH="$PATH:~/hmmer-3.3.2/bin"
          cd ..

      - name: Run program
        run: python3 main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            model.hmm
            PFseed.txt
            result.out
            id_list.txt
            protein_for_target_id.fasta
